### PR TITLE
Draft for AbstractReader.py.

### PR DESCRIPTION
**Pull request by dlacoste-esrf**
This version is just a draft open for discussion.

Some of the changes:
Removed the get_database method. This would be purely implementation related… If one needs to do something else than extract data then it should create it's own connector, I don't understand the need to expose this.
Created an enum for the aggregation functions. These are the one we support in timescaledb. I think it should contain all the aggregation functions that are supported in any of our backends. All custom aggregation should then be shared and not be linked to the backend.
Removed the correlated argument, for more or less the same reason, this can and should be shared between all the backends. I am actually interested in knowing if we could do this at the DB level, I believe we can, so we might want it back.
Added some documentation on the expected format and so on. I have no idea about the performances of the underlying containers, we might want to change it (some suggested the use of pandas).

### CODE REVIEW

**Comment by sergirubio** [comment]
Hi Damien,

I'm still concerned about the removal of the get_database method. In many different applications we've found the need to reuse the existing connection instead of creating new ones for each querie. Exposing the connection object would also allow to reuse it to perform operations that are not implemented. It may be renamed to get_connection but we need it still present in order to perform these operations that this simplified-api do not provide.

Regarding the enumeration, I've find it useful to have it. I would add FIRST and LAST aggregators as we use it frequently. backends can just redefine the enum or expand it in case more aggregators are needed.

Regarding the correlate argument, we may rename it as it meaning may be not clear. When aggregating the data for multiple attributes it may occur that the number of points of each array returned do not have the same size, typically if an attribute had no data in one of the aggregation intervals. 

Although we can use python in the client side to "fill the gaps", many DB's can do this faster on the server side. We use heavily this option to provide data in an scan-like format, and it's a feature that we cannot drop from the API. An argument called "fill=True/False" would have been less ambiguous.

If you agree, we can replace it by adding a **params argument to get_attribute(s)_values methods, so arguments can be passed to the methods without enforcing it to be implemented (although we will need to implement it for TimeScaleDB).

So, may comments would summarize as:
 - keep get_database method, maybe rename it to get_connection
 - add FIRST and LAST aggregators (returning either the first or the last value in the interval).
 - replace correlate argument by a **params dictionary, allowing to pass custom parameters to implementations.

Sorry for the delay on answering,

Sergi

**Comment by dlacoste-esrf** [comment]
Ok
So I readded the get_connection method, but I'd really like to find alternatives to that… What if a client then close the connection ? it will be a bit annoying… And, again, implementation specific…

Added the first and Last aggregates, we have to make sure the time is flowing in the same direction for everyone for these, it could be misleading otherwise.
The **params is a good idea, as is the correlate argument, if it can be done in the db. I have no clue about timescaledb for this but I'll check. So I put both.

**Comment by dlacoste-esrf** [comment]
Hi,
I am thinking that we need to add a field to extract only some indexes from an array when querying an attribute. We can add a field to the dict, but maybe defining a custom structure might be more convenient/extensible/maintanable ?
As for the correlate parameter, I am having second thoughts as it is not as simple… This feature need some parameters in itself ! Do we fill the gaps with the latest, next or an interpolated value, for starter. Or do we want to fill all the gaps or simply align all data on one attribute, or have them all on the same sampling interval that could be something else entirely…
What do you think?

**Comment by sergirubio** [comment]
Hi Damien, sorry for late answer, I had some short holidays

Regarding the index on arrays, at Alba we use an index passed with the model itself :+1: 

tango://host:10000/my/device/server/spectrum[i]

If index is present, only those values are returned as if an scalar was asked. If no index is passed, then the whole array is returned for each timestamp.

Regarding the correlate argument, our export methods at Alba use an integer time as value for correlate. So all gaps are by default filled by returning timestamps that are multiple of the argument and the latest value for each attribute.

This implementation is quite ad-hoc; but a way to standardize it would be:

.. code::

  correlate=True,
    **params['period']=int, # 1 by default?
    **params['aggregator']=max, #max/last/next/average/...

My idea here is that returning values at a fixed period is something that the DB engine can do for us; and if something more complex is need to be done (e.g. interpolation) then it should be done with correlate=False (raw data) and then post-processing the data in the client.

But, as we see here, this usage clearly overlaps with the decimation argument we proposed before, so maybe we can just simplify and redux the behaviour with arguments like:

.. code::

  def get_attribute_values(attribute,
    period=3, #an integer, the period in seconds to aggregate/decimate values
    aggregator=max, #the method used to aggregate values within the interval

These two arguments would be common for get_attribute_values and get_attributes_values; but we must ensure for the second case that the timestamps of the values returned are the same for all attributes (e.g. grouping by "timestamp mod period" when querying).

This would override the decimate argument (period=0 would mean raw data); and will leave the matter of removing repeated values or filling the gaps to another method of the API that will be DB-agnostic.

What do you think of this solution?

Sergi

**Comment by dlacoste-esrf** [comment]
Hi Sergi,

Ok for the indexes. I am not a big fan of doing like this cause then we will have to parse the attribute name to extract the index… We will need to fix the syntax then. What about querying several indexes for example ?
From the rest of the discussion I am really starting to lean towards defining a specific structure to store the query input.
Your second proposal should already be possible with the current interface using get_attributes_values as for the input we expect something like: 
{
attr_name: {period: [aggr1, aggr2, …], …}
}
we already have the period and aggregates, or am I missing something ? (side note we could add indexes there, but it becomes messy, so it might call for a dedicated data model)

As for the correlation, I understood you wanted to query, some parameters, and fill the gaps so all timestamps for every attributes have a value for all attributes. In the end this is not the case, am I right ?
In the end it might not matter much as I had a look, and this exists in the current java viewer, but it can be done in the db, so it might be interesting to have this feature anyway… As well as a flag to remove null (errors) values.

**Comment by dlacoste-esrf** [comment]
ping.
Any news on this ?

**Comment by sergirubio** [comment]
ups, sorry damien, I just came back from holidays ... I'll have a look into it

**Comment by sergirubio** [comment]
Hi Damien,

Sorry for the late replies ... whenever we have urgent issues I got disconnected from developing, sorry.

Regarding this syntax:
{
attr_name: {period: [aggr1, aggr2, …], …}
}

I'am not really sure what period stands for in here, is it meant to be an integer? are we going to extract an attribute for multiple periods?

I think that when extracting several attributes we should use the same aggregator for all, because if not is almost impossible to optimize and there's no sense in making a common call instead of multiple get_attribute_values.

Regarding "filling the gaps"  on correlated series, it is a common feature that we have been asked for in order to find all values of attributes at a given timestamp .. this is specially used when searching the cause of an event in the machine; and as it may mix non-numeric types we tipically extract the data to .csv instead of plotting at all.

I think that as long as we agree on the attributes dictionary format we can proceed to accept and publish the draft and start with an implementation.

In fact, I would suggest that attributes may be a dictionary ... or just a list; in the case of a list then it would assign default values to params and move on.

What do you think?

Sergi

**Comment by dlacoste-esrf** [comment]
Hi Sergi,

ideally the period is a timedelta, lets say you want aggregation on 1min or 1day, you would use a timedelta of these values. My approach is coming from the backend implementation, we can do it like this, so why not do it. But from a user point of view your approach is better I believe. We could use the same input as for the get_attribute_value then, just using a list instead ? It's the same for the start_date and end_date, I suppose in almost all cases they will be the same.
We can then add an argument to activate data correlation or not (deactivated by default), and we are good to go, using a list for the attributes on a multiple query.
I'll push the modifications soon.

**Comment by sergirubio** [comment]
Hi Damien,

I made a pull request to your repo with some changes on AbstractReader and a demo implementation for MariaDB, not very optimized but with a main() that already allows to use it from shell. Tomorrow I can make a fast demo.

Sergi

**Comment by sergirubio** [comment]
This pull request have become a separated project, see: https://www.gitlab.com/tango-controls/hdbpp/libhdbpp-python

**Pull request closed without merging**
